apiVersion: eksctl.io/v1alpha4
kind: ClusterConfig

metadata:
  name: gpu-cpu-cluster
  region: us-west-2

nodeGroups:
  - name: ng-gpu
    labels: {role: gpu}
    instanceType: p3.8xlarge
    desiredCapacity: 2
  - name: ng-cpu
    labels: {role: cpu}
    instanceType: m5.2xlarge
    desiredCapacity: 4

